spring.application.name=BookMyShow

spring.datasource.url=jdbc:mysql://localhost:3306/BookMyShow?createDataBaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=system

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080

spring.main.allow-bean-definition-overriding=true